// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYE_WeC0bmJxceHMD3xDDvPBSDIPL47g',
    appId: '1:339793866787:web:62babc6eb6c152cec58196',
    messagingSenderId: '339793866787',
    projectId: 'dee-s-budget-app',
    authDomain: 'dee-s-budget-app.firebaseapp.com',
    databaseURL: 'https://dee-s-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'dee-s-budget-app.firebasestorage.app',
    measurementId: 'G-CT8X8D06MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGvJnHRmKFK2RYTjgJ_ECOFPKSFCaiH8',
    appId: '1:339793866787:android:f20d35fcd26c25e9c58196',
    messagingSenderId: '339793866787',
    projectId: 'dee-s-budget-app',
    databaseURL: 'https://dee-s-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'dee-s-budget-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAxcGgSc_ek0AqJM-nuMCva1vHA5wIdF4',
    appId: '1:339793866787:ios:996581593558be71c58196',
    messagingSenderId: '339793866787',
    projectId: 'dee-s-budget-app',
    databaseURL: 'https://dee-s-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'dee-s-budget-app.firebasestorage.app',
    iosBundleId: 'com.io.budgetTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAxcGgSc_ek0AqJM-nuMCva1vHA5wIdF4',
    appId: '1:339793866787:ios:996581593558be71c58196',
    messagingSenderId: '339793866787',
    projectId: 'dee-s-budget-app',
    databaseURL: 'https://dee-s-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'dee-s-budget-app.firebasestorage.app',
    iosBundleId: 'com.io.budgetTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYE_WeC0bmJxceHMD3xDDvPBSDIPL47g',
    appId: '1:339793866787:web:6a39966e44eb74f2c58196',
    messagingSenderId: '339793866787',
    projectId: 'dee-s-budget-app',
    authDomain: 'dee-s-budget-app.firebaseapp.com',
    databaseURL: 'https://dee-s-budget-app-default-rtdb.firebaseio.com',
    storageBucket: 'dee-s-budget-app.firebasestorage.app',
    measurementId: 'G-3YR1MPE416',
  );
}
